### ISSUE TITLE
Issue to access userlogin

### ISSUE THREAD

**Issue by devopsdymyr** [gsacavdm/gov-k8-nifi#1]
![image](https://user-images.githubusercontent.com/41105507/59657919-c1efa580-91bf-11e9-894f-dac7fa0f3a63.png)

**Comment by gsacavdm** [comment]
This is expected, as per Nifi's [User Authentication](https://nifi.apache.org/docs/nifi-registry-docs/html/administration-guide.html#user_authentication) documentation

> NiFi Registry does not perform user authentication over HTTP. Using HTTP, all users will have full permissions. 

You'll need to do something like what's outlined in this [NiFi Registry behind nginx proxy with (client) SSL/TLS and basic auth](https://michalklempa.com/2019/04/nifi-registry-nginx-proxy-tls-basic-auth/) article to setup auth on the nginx-side.
